"""empty message

Revision ID: 269feb08d5b7
Revises: 2466efcd1f8e
Create Date: 2024-09-04 20:08:46.334096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269feb08d5b7'
down_revision = '2466efcd1f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas_publicadas_ingredients',
    sa.Column('receta_publicada_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['receta_publicada_id'], ['receta_publicada.id'], ),
    sa.PrimaryKeyConstraint('receta_publicada_id', 'ingredient_id')
    )
    with op.batch_alter_table('categoria_recepies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receta_publicada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'receta_publicada', ['receta_publicada_id'], ['id'])

    with op.batch_alter_table('recepies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_official', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('steps', sa.String(length=255), nullable=False))

    with op.batch_alter_table('receta_publicada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('steps', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_official', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('receta_publicada_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('title')
        batch_op.drop_column('author_id')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receta_publicada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('receta_publicada_author_id_fkey', 'user', ['author_id'], ['id'])
        batch_op.drop_column('is_official')
        batch_op.drop_column('user_id')
        batch_op.drop_column('steps')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('recepies', schema=None) as batch_op:
        batch_op.drop_column('steps')
        batch_op.drop_column('description')
        batch_op.drop_column('is_official')

    with op.batch_alter_table('categoria_recepies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receta_publicada_id')

    op.drop_table('recetas_publicadas_ingredients')
    # ### end Alembic commands ###
