"""empty message

Revision ID: 310c03eceea1
Revises: cf9da070ae4f
Create Date: 2024-09-02 18:38:12.508213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310c03eceea1'
down_revision = 'cf9da070ae4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_users',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_users')
    # ### end Alembic commands ###
