"""empty message

Revision ID: 616ad979d6ad
Revises: 269feb08d5b7
Create Date: 2024-09-04 20:45:29.553169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616ad979d6ad'
down_revision = '269feb08d5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas_publicadas_categorias',
    sa.Column('receta_publicada_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['receta_publicada_id'], ['receta_publicada.id'], ),
    sa.PrimaryKeyConstraint('receta_publicada_id', 'categoria_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas_publicadas_categorias')
    # ### end Alembic commands ###
