"""empty message

Revision ID: 6482483705dc
Revises: d734e8ce59e8
Create Date: 2024-09-10 12:09:35.254944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6482483705dc'
down_revision = 'd734e8ce59e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
