"""empty message

Revision ID: aa3aaa052038
Revises: 25e1d473aaf2
Create Date: 2024-08-21 10:25:09.029839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3aaa052038'
down_revision = '25e1d473aaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepies_ingredients')
    op.drop_table('ingredients')
    op.drop_table('categoria_recepies')
    op.drop_table('favorite_recepies')
    op.drop_table('recepies')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('recepies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('recepies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='recepies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('favorite_recepies',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recepy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recepy_id'], ['recepies.id'], name='favorite_recepies_recepy_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_recepies_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'recepy_id', name='favorite_recepies_pkey')
    )
    op.create_table('categoria_recepies',
    sa.Column('recepy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['category.id'], name='categoria_recepies_categoria_id_fkey'),
    sa.ForeignKeyConstraint(['recepy_id'], ['recepies.id'], name='categoria_recepies_recepy_id_fkey'),
    sa.PrimaryKeyConstraint('recepy_id', 'categoria_id', name='categoria_recepies_pkey')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ingredients_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ingredients_pkey'),
    sa.UniqueConstraint('name', name='ingredients_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('recepies_ingredients',
    sa.Column('recepy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='recepies_ingredients_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['recepy_id'], ['recepies.id'], name='recepies_ingredients_recepy_id_fkey'),
    sa.PrimaryKeyConstraint('recepy_id', 'ingredient_id', name='recepies_ingredients_pkey')
    )
    # ### end Alembic commands ###
